public enum TokenType {
    KLASSE, TYP, VOID, WENN, SONST, FUER, SOLANGE, RUECKGABE, NEU,
    BLOCK_AUF, BLOCK_ZU, KLAMMER_AUF, KLAMMER_ZU, ECKIGE_AUF, ECKIGE_ZU,
    SEMIKOLON, KOMMA, PUNKT,
    ZUWEISUNGS_OP, VERGLEICHS_OP, ARITHMETIK_OP, NOT,
    ZAHL, NAME, STRING_LITERAL,
    UNBEKANNT, EOF
}